# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.6.x'
    checkLatest: true
- task: Yarn@3
  inputs:
    arguments: 'install'
- task: Yarn@3
  inputs:
    arguments: 'build'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'buil'
    ArtifactName: 'table-wrapper'
    publishLocation: 'Container'